language: java
jdk: oraclejdk7

before_install:
  # Maven 3.2.1
  - wget http://www.us.apache.org/dist/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz
  - tar xvf apache-maven-3.2.1-bin.tar.gz > /dev/null
  - export MVN_HOME=`pwd`/apache-maven-3.2.1
  - export PATH=${MVN_HOME}/bin/:${PATH}
  - mvn --version

script: mvn clean package

after_script:
  # Unit tests go here
