name: Report PR Test Coverage

on:
  workflow_run:
    workflows:
    - Tests CI
    types:
    - completed

permissions: { }

jobs:
  publish:
    name: Report Coverage
    runs-on: ubuntu-latest
    if: |-
      github.event.workflow_run.event == 'pull_request'
        && github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download PR test coverage report
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # tag=v7.0.0
      with:
        name: pr-test-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
    - name: Report Coverage to Codacy
      run: |-
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          --project-token ${{ secrets.CODACY_PROJECT_TOKEN }} \
          --commit-uuid ${{ github.event.workflow_run.head_sha }} \
          --coverage-reports ./target/jacoco-ut/jacoco.xml \
          --language Java
